(function(g){
'use strict';
const A=g.Akses,U=g.PortalUI,D=g.TrackingDomain,e=U.escape,$=id=>document.getElementById(id),P=g.Paginasi;
function warning(note,today=D.today()){
 if(note.status!=='Aktif'||!note.tanggal_pengingat)return {kind:'',label:''};
 const days=D.dayNumber(note.tanggal_pengingat)-D.dayNumber(today);
 return days<0?{kind:'late',label:'Tanggal terlewat'}:days===0?{kind:'today',label:'Hari ini'}:days<=3?{kind:'near',label:'Mendekati tanggal'}:{kind:'',label:''};
}
g.AgendaDomain=Object.freeze({warning});
const host=$('agenda-page');host.innerHTML=`<header class="page-heading"><div><h1>Tamu &amp; Catatan</h1><p class="page-description">Kunjungan site dan informasi untuk petugas.</p></div><button class="button button-primary" id="agenda-add" type="button">Tambah tamu</button></header>
<div class="panel agenda-panel"><div class="agenda-tabs" role="tablist" aria-label="Tamu dan catatan">${[['tamu','Tamu'],['catatan','Catatan Admin'],['simpan','Simpan']].map(([id,label],i)=>`<button id="agenda-tab-${id}" role="tab" aria-controls="agenda-results" aria-selected="${i===0}" tabindex="${i===0?0:-1}" type="button" data-agenda-tab="${id}">${label}</button>`).join('')}</div>
<div class="agenda-toolbar"><div class="field agenda-search"><label for="agenda-search">Cari</label><input type="search" id="agenda-search" maxlength="200" placeholder="Nama, asal, atau isi note…"></div><div class="field" id="agenda-view-field"><label for="agenda-view">Tampilkan</label><select id="agenda-view"><option value="aktif">Aktif</option><option value="riwayat">Riwayat</option></select></div><div class="field"><label for="agenda-category">Jenis</label><select id="agenda-category"></select></div><button class="button button-secondary" id="agenda-refresh" type="button">Muat ulang</button></div>
<p id="agenda-saved-help" class="agenda-saved-help" hidden>Hanya data yang dipilih masuk ke Simpan. Data ini dipertahankan sampai dihapus oleh Administrator.</p><p id="agenda-error" class="form-error" role="alert" hidden></p><span id="agenda-count" class="agenda-count" role="status"></span><div id="agenda-results" role="tabpanel" aria-labelledby="agenda-tab-tamu"></div><div id="agenda-pages" class="pagination"></div></div>`;
function makeDialog(id,title,body){const node=document.createElement('dialog');node.id=id;node.className='form-dialog agenda-dialog';node.setAttribute('aria-labelledby',id+'-title');node.innerHTML=`<div class="dialog-heading"><h2 id="${id}-title">${title}</h2><button type="button" class="icon-button" data-agenda-close="${id}" aria-label="Tutup">${U.icon('close')}</button></div><form id="${id}-form"><div class="form-body"><p class="actor-line">Petugas <strong data-current-user></strong></p><div class="form-grid">${body}</div><p id="${id}-error" class="form-error" role="alert" hidden></p></div><div class="dialog-actions"><button type="button" class="button button-secondary" data-agenda-close="${id}">Batal</button><button type="submit" class="button button-primary">Simpan</button></div></form>`;document.body.append(node);return node;}
const guestDialog=makeDialog('tamu-dialog','Tambah tamu',`<div class="field"><label for="tamu-jenis">Jenis kunjungan</label><select id="tamu-jenis" name="jenis"><option>Tamu</option><option>Vendor</option></select></div><div class="field" id="tamu-jumlah-field"><label for="tamu-jumlah">Jumlah orang</label><select id="tamu-jumlah">${Array.from({length:10},(_,i)=>`<option>${i+1}</option>`).join('')}</select></div><div class="full-width" id="tamu-orang"></div><div class="field"><label for="tamu-asal">Tamu dari mana</label><input id="tamu-asal" name="asal" maxlength="200"></div><div class="field"><label for="tamu-tanggal">Tanggal kedatangan <span class="required">*</span></label><input id="tamu-tanggal" name="tanggal_kedatangan" type="date" required></div><div class="field"><label for="tamu-status">Status <span class="required">*</span></label><select id="tamu-status" name="status" required><option>Akan Datang</option><option>Sudah Datang</option><option>Keluar Site</option><option>Batal</option></select></div><div class="field full-width" id="tamu-keluar-field" hidden><label for="tamu-keluar">Tanggal keluar site <span class="required">*</span></label><input id="tamu-keluar" name="tanggal_keluar" type="date"></div><div class="field full-width"><label for="tamu-keperluan">Keperluan</label><input id="tamu-keperluan" name="keperluan" maxlength="500"></div><div class="field full-width"><label for="tamu-note">Note</label><textarea id="tamu-note" name="catatan" rows="4" maxlength="3000"></textarea></div>`);
const noteDialog=makeDialog('catatan-dialog','Tambah catatan',`<div class="field full-width"><label for="catatan-jenis">Jenis catatan <span class="required">*</span></label><select id="catatan-jenis" name="jenis" required><option>Administrasi Karyawan</option><option>Pengingat</option></select></div><div class="field full-width" id="catatan-employee-picker"></div><div class="field full-width"><label class="agenda-check"><input type="checkbox" id="catatan-pakai-tanggal"> Gunakan tanggal pengingat</label></div><div class="field full-width" id="catatan-tanggal-field" hidden><label for="catatan-tanggal">Tanggal pengingat <span class="required">*</span></label><input id="catatan-tanggal" name="tanggal_pengingat" type="date"></div><div class="field full-width"><label for="catatan-note">Note <span class="required">*</span></label><textarea id="catatan-note" name="catatan" rows="5" required maxlength="3000"></textarea></div>`);
const picker=g.EmployeeUI.createPicker('catatan-employee','Karyawan',{allowAdmin:false,allowExistingInactive:true});
let rows=[],tab='tamu',page=1,total=0,editingGuest=null,editingNote=null,request=0,batchKey='',searchTimer;
const stamp=v=>v?new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jayapura',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))+' WIT':'—';
const guestActive=v=>!['Keluar Site','Batal'].includes(v.status);
function error(id,msg){$(id).textContent=msg;$(id).hidden=!msg;}
function saveButton(v,kind){return v.disimpan?'<span class="agenda-saved-badge">Tersimpan</span>':(kind==='catatan'||v.status==='Keluar Site')?`<button class="button button-secondary" type="button" data-agenda-save="${kind}" data-agenda-id="${e(v.id)}">Masukkan Simpan</button>`:'';}
function metadata(v){return `<div class="agenda-meta"><span>Dibuat oleh <strong>${e(v.nama_pembuat)}</strong> · ${e(stamp(v.dibuat_pada))}</span>${v.diubah_pada&&v.diubah_pada!==v.dibuat_pada?`<span>Diubah oleh ${e(v.nama_pengubah)} · ${e(stamp(v.diubah_pada))}</span>`:''}${v.disimpan?`<span>Disimpan oleh ${e(v.nama_penyimpan||'—')} · ${e(stamp(v.disimpan_pada))}</span>`:''}</div>`;}
function guestCard(v){return `<article class="agenda-item guest-item"><header class="agenda-item-header"><div><span class="agenda-kind">${e(v.jenis||'Tamu')}</span><h2>${e(v.nama)}</h2><p class="guest-origin">${e([v.jabatan,v.asal].filter(Boolean).join(' · ')||'Asal belum diisi')}</p></div><span class="status-badge">${e(v.status)}</span></header><div class="guest-dates"><div><span>Kedatangan</span><strong>${e(U.dateText(v.tanggal_kedatangan))}</strong></div><div><span>Keluar site</span><strong>${e(U.dateText(v.tanggal_keluar))}</strong></div></div><div class="guest-notes"><div><span class="agenda-label">Keperluan</span><p>${e(v.keperluan||'—')}</p></div><div><span class="agenda-label">Note</span><p class="agenda-note">${e(v.catatan||'—')}</p></div></div><footer>${metadata(v)}<div class="agenda-actions"><button type="button" class="button button-secondary" data-tamu-edit="${e(v.id)}">${guestActive(v)?'Edit / Keluar site':'Edit tamu'}</button>${saveButton(v,'tamu')}${g.DataAdmin.buttons('tamu',v.id,v.versi,v.nama)}</div></footer></article>`;}
function noteCard(v){const w=warning(v);return `<article class="agenda-item note-item ${w.kind}"><header class="agenda-item-header"><div><span class="agenda-kind">${e(v.jenis)}</span><h2>${e(v.jenis==='Administrasi Karyawan'?v.nama_karyawan||'Karyawan':'Pengingat')}</h2>${v.nik_karyawan?`<p class="guest-origin">${e(v.nik_karyawan)}</p>`:''}</div><span class="${w.label?'agenda-warning '+w.kind:'status-badge'}">${e(w.label||v.status)}</span></header><p class="agenda-reminder-date">${v.tanggal_pengingat?'Tanggal pengingat: '+e(U.dateText(v.tanggal_pengingat)):'Tanpa tanggal pengingat'}</p><p class="agenda-note note-content">${e(v.catatan)}</p><footer>${metadata(v)}${v.status==='Selesai'?`<p class="agenda-completion">Diselesaikan oleh <strong>${e(v.nama_penyelesai)}</strong> · ${e(stamp(v.diselesaikan_pada))}</p>`:''}<div class="agenda-actions">${v.status==='Aktif'?`<button class="button button-primary" type="button" data-note-status="Selesai" data-note-id="${e(v.id)}">Tandai Selesai</button><button class="button button-secondary" type="button" data-note-edit="${e(v.id)}">Edit catatan</button>`:A.administrator()?`<button class="button button-secondary" type="button" data-note-status="Aktif" data-note-id="${e(v.id)}">Buka kembali</button>`:''}${saveButton(v,'catatan')}${g.DataAdmin.buttons('catatan',v.id,v.versi,v.catatan.slice(0,100))}</div></footer></article>`;}
function render(){
 $('agenda-add').hidden=!A.canWrite()||tab==='simpan';
 $('agenda-results').innerHTML=!A.canWrite()?'<p class="agenda-empty">Halaman ini tersedia untuk admin dengan akses Portal.</p>':rows.length?`<div class="agenda-items">${rows.map(v=>v._kelompok==='tamu'?guestCard(v):noteCard(v)).join('')}</div>`:'<p class="agenda-empty">Belum ada data yang sesuai pilihan ini.</p>';
 const range=P.range(total,page);$('agenda-count').textContent=P.summary(range);P.render($('agenda-pages'),range,n=>{page=n;refresh(true);},false);
}
async function refresh(force=false){
 if(!force&&location.hash!=='#agenda')return;
 const n=++request;await A.ready;if(!A.canWrite()){rows=[];total=0;render();return;}
 $('agenda-results').setAttribute('aria-busy','true');
 try{const result=await A.rpc('halaman_agenda',{p_tab:tab,p_tampilan:$('agenda-view').value,p_jenis:$('agenda-category').value,p_cari:$('agenda-search').value.trim(),p_halaman:page});if(n!==request||!A.canWrite())return;rows=result.data;total=result.total;page=result.halaman;error('agenda-error','');render();}
 catch(err){if(n===request)error('agenda-error',err.message);}finally{if(n===request)$('agenda-results').setAttribute('aria-busy','false');}
}
function selectTab(next,load=true){
 tab=next;page=1;rows=[];total=0;$('agenda-view').value='aktif';$('agenda-view-field').hidden=tab==='simpan';$('agenda-saved-help').hidden=tab!=='simpan';$('agenda-view').options[1].textContent=tab==='tamu'?'Riwayat':'Selesai';$('agenda-add').textContent=tab==='tamu'?'Tambah tamu':'Tambah catatan';
 const kinds=tab==='tamu'?['Tamu','Vendor']:tab==='catatan'?['Administrasi Karyawan','Pengingat']:['Tamu','Vendor','Catatan'];$('agenda-category').innerHTML='<option value="">Semua jenis</option>'+kinds.map(k=>`<option value="${k==='Catatan'?'catatan':k}">${k}</option>`).join('');
 document.querySelectorAll('[data-agenda-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.agendaTab===tab));b.tabIndex=b.dataset.agendaTab===tab?0:-1;});$('agenda-results').setAttribute('aria-labelledby','agenda-tab-'+tab);render();if(load)refresh(true);
}
function guestStatus(){const out=$('tamu-status').value==='Keluar Site';$('tamu-keluar-field').hidden=!out;$('tamu-keluar').required=out;$('tamu-keluar').disabled=!out;$('tamu-keluar').min=$('tamu-tanggal').value;$('tamu-keluar').max=D.today();if(!out)$('tamu-keluar').value='';}
function people(values){const old=values||[...document.querySelectorAll('[data-guest-person]')].map(el=>({nama:el.querySelector('[data-guest-name]').value,jabatan:el.querySelector('[data-guest-job]').value}));const count=editingGuest?1:Number($('tamu-jumlah').value);$('tamu-orang').innerHTML=Array.from({length:count},(_,i)=>`<fieldset class="guest-person" data-guest-person><legend>Orang ${i+1}</legend><div class="form-grid"><div class="field"><label for="tamu-nama-${i}">Nama <span class="required">*</span></label><input id="tamu-nama-${i}" data-guest-name value="${e(old[i]?.nama||'')}" required maxlength="150"></div><div class="field"><label for="tamu-jabatan-${i}">Jabatan</label><input id="tamu-jabatan-${i}" data-guest-job value="${e(old[i]?.jabatan||'')}" maxlength="150"></div></div></fieldset>`).join('');}
function noteType(){const employee=$('catatan-jenis').value==='Administrasi Karyawan';$('catatan-employee-picker').hidden=!employee;picker.setDisabled(!employee);const dated=$('catatan-pakai-tanggal').checked;$('catatan-tanggal-field').hidden=!dated;$('catatan-tanggal').required=dated;$('catatan-tanggal').disabled=!dated;}
async function guestForm(id){
 if(!A.canWrite())return;editingGuest=id?await A.one('tamu',id):null;batchKey=crypto.randomUUID();const f=$('tamu-dialog-form');f.reset();for(const el of f.elements)if(el.name)el.value=editingGuest?.[el.name]??({tanggal_kedatangan:D.today(),status:'Akan Datang',jenis:'Tamu'}[el.name]||'');$('tamu-jumlah').value='1';$('tamu-jumlah-field').hidden=!!id;people(editingGuest?[editingGuest]:[]);guestStatus();$('tamu-dialog-title').textContent=id?'Edit kunjungan':'Tambah kunjungan';error('tamu-dialog-error','');guestDialog.querySelector('[data-current-user]').textContent=A.profile?.nama||'';guestDialog.showModal();g.FormGuard?.clean(f);$('tamu-nama-0').focus();
}
async function noteForm(id){if(!A.canWrite())return;editingNote=id?await A.one('catatan_admin',id):null;const f=$('catatan-dialog-form');f.reset();$('catatan-jenis').value=editingNote?.jenis||'Administrasi Karyawan';$('catatan-pakai-tanggal').checked=!!editingNote?.tanggal_pengingat;$('catatan-tanggal').value=editingNote?.tanggal_pengingat||'';$('catatan-note').value=editingNote?.catatan||'';await picker.load(editingNote?.karyawan_id||'');noteType();$('catatan-dialog-title').textContent=id?'Edit catatan':'Tambah catatan';error('catatan-dialog-error','');noteDialog.querySelector('[data-current-user]').textContent=A.profile?.nama||'';noteDialog.showModal();g.FormGuard?.clean(f);$('catatan-jenis').focus();}
$('agenda-add').onclick=()=>{(tab==='tamu'?guestForm():noteForm()).catch(err=>error('agenda-error',err.message));};
$('agenda-refresh').onclick=()=>refresh(true);$('agenda-view').onchange=$('agenda-category').onchange=()=>{page=1;refresh(true);};$('agenda-search').oninput=()=>{clearTimeout(searchTimer);request++;searchTimer=setTimeout(()=>{page=1;refresh(true);},300);};
$('tamu-status').onchange=$('tamu-tanggal').onchange=guestStatus;$('tamu-jumlah').onchange=()=>people();$('catatan-jenis').onchange=$('catatan-pakai-tanggal').onchange=noteType;
document.querySelectorAll('[data-agenda-close]').forEach(b=>b.onclick=()=>{const d=$(b.dataset.agendaClose);if(!g.FormGuard||g.FormGuard.leave(d))d.close();});
document.querySelectorAll('[data-agenda-tab]').forEach(b=>{b.onclick=()=>selectTab(b.dataset.agendaTab);b.onkeydown=ev=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(ev.key)){ev.preventDefault();const tabs=['tamu','catatan','simpan'],i=tabs.indexOf(tab);selectTab(tabs[ev.key==='Home'?0:ev.key==='End'?2:(i+(ev.key==='ArrowRight'?1:2))%3]);$('agenda-tab-'+tab).focus();}};});
host.addEventListener('click',async event=>{
 const guest=event.target.closest('[data-tamu-edit]'),note=event.target.closest('[data-note-edit]'),done=event.target.closest('[data-note-status]'),save=event.target.closest('[data-agenda-save]'),b=done||save;
 if(b?.disabled)return;try{if(guest)await guestForm(guest.dataset.tamuEdit);if(note)await noteForm(note.dataset.noteEdit);if(b){b.disabled=true;const v=rows.find(n=>n.id===(done?done.dataset.noteId:save.dataset.agendaId));if(!v)throw new Error('Muat ulang daftar terlebih dahulu.');if(done)await A.rpc('ubah_status_catatan',{p_id:v.id,p_versi:v.versi,p_status:done.dataset.noteStatus},true);else await A.rpc('tandai_simpan_agenda',{p_id:v.id,p_versi:v.versi,p_jenis:save.dataset.agendaSave},true);await refresh(true);U.showToast(done?'Status catatan tersimpan.':'Data masuk ke Simpan.');}}
 catch(err){error('agenda-error',err.message);}finally{if(b)b.disabled=false;}
});
for(const kind of ['tamu','catatan']){$(kind+'-dialog-form').onsubmit=async event=>{
 event.preventDefault();const f=event.currentTarget,b=f.querySelector('[type=submit]');if(b.disabled||!f.reportValidity())return;b.disabled=true;
 try{const data=Object.fromEntries(new FormData(f)),old=kind==='tamu'?editingGuest:editingNote;
 if(kind==='tamu'){const people=[...document.querySelectorAll('[data-guest-person]')].map(el=>({nama:el.querySelector('[data-guest-name]').value.trim(),jabatan:el.querySelector('[data-guest-job]').value.trim()}));if(old)await A.rpc('simpan_tamu',{p_data:{...data,...people[0]},p_id:old.id,p_versi:old.versi},true);else await A.rpc('tambah_rombongan_tamu',{p_bersama:data,p_tamu:people,p_kunci:batchKey},true);}
 else{data.karyawan_id=data.jenis==='Administrasi Karyawan'?picker.read().employeeId:null;await A.rpc('simpan_catatan_admin',{p_data:data,...(old?{p_id:old.id,p_versi:old.versi}:{})},true);}
 g.FormGuard?.clean(f);$(kind+'-dialog').close();await refresh(true);U.showToast(kind==='tamu'?'Kunjungan tersimpan.':'Catatan tersimpan.');}
 catch(err){error(kind+'-dialog-error',err.message);}finally{b.disabled=false;}
};}
for(const name of ['data:muat-ulang','employees:changed'])document.addEventListener(name,()=>refresh());
document.addEventListener('akses:berubah',()=>{request++;if(!A.canWrite()){rows=[];total=0;render();guestDialog.close();noteDialog.close();}else refresh();});
window.addEventListener('hashchange',()=>refresh());document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});setInterval(()=>{if(!document.hidden)refresh();},60000);selectTab('tamu',false);refresh();
})(window);
