(function(g){
'use strict';
const A=g.Akses,U=g.PortalUI,D=g.TrackingDomain,e=U.escape,$=id=>document.getElementById(id);
function warning(note,today=D.today()){
 if(note.jenis!=='Pengingat'||note.status!=='Aktif'||!note.tanggal_pengingat)return {kind:'',label:''};
 const days=D.dayNumber(note.tanggal_pengingat)-D.dayNumber(today);
 return days<0?{kind:'late',label:'Tanggal terlewat'}:days===0?{kind:'today',label:'Hari ini'}:days<=3?{kind:'near',label:'Mendekati tanggal'}:{kind:'',label:''};
}
g.AgendaDomain=Object.freeze({warning});
const host=$('agenda-page');host.innerHTML=`<header class="page-heading"><div><h1>Tamu &amp; Catatan</h1><p class="page-description">Kedatangan tamu dan informasi untuk admin.</p></div><button class="button button-primary" id="agenda-add" type="button">Tambah tamu</button></header>
<div class="panel agenda-panel"><div class="agenda-tabs" role="tablist" aria-label="Tamu dan catatan"><button id="agenda-tab-tamu" role="tab" aria-controls="agenda-results" aria-selected="true" type="button" data-agenda-tab="tamu">Tamu</button><button id="agenda-tab-catatan" role="tab" aria-controls="agenda-results" aria-selected="false" tabindex="-1" type="button" data-agenda-tab="catatan">Catatan Admin</button></div>
<div class="agenda-toolbar"><div class="field"><label for="agenda-view">Tampilkan</label><select id="agenda-view"><option value="aktif">Aktif</option><option value="riwayat">Riwayat</option></select></div><div class="field" id="agenda-category-field" hidden><label for="agenda-category">Jenis catatan</label><select id="agenda-category"><option value="">Semua jenis</option><option>Administrasi Karyawan</option><option>Pengingat</option></select></div><span id="agenda-count" role="status"></span><button class="button button-secondary" id="agenda-refresh" type="button">Muat ulang</button></div>
<p id="agenda-error" class="form-error" role="alert" hidden></p><div id="agenda-results" role="tabpanel" aria-labelledby="agenda-tab-tamu"></div></div>`;
function makeDialog(id,title,body){const node=document.createElement('dialog');node.id=id;node.className='form-dialog agenda-dialog';node.setAttribute('aria-labelledby',id+'-title');node.innerHTML=`<div class="dialog-heading"><h2 id="${id}-title">${title}</h2><button type="button" class="icon-button" data-agenda-close="${id}" aria-label="Tutup">${U.icon('close')}</button></div><form id="${id}-form"><div class="form-body"><p class="actor-line">Petugas <strong data-current-user></strong></p><div class="form-grid">${body}</div><p id="${id}-error" class="form-error" role="alert" hidden></p></div><div class="dialog-actions"><button type="button" class="button button-secondary" data-agenda-close="${id}">Batal</button><button type="submit" class="button button-primary">Simpan</button></div></form>`;document.body.append(node);return node;}
const guestDialog=makeDialog('tamu-dialog','Tambah tamu',`<div class="field"><label for="tamu-nama">Nama tamu <span class="required">*</span></label><input id="tamu-nama" name="nama" required maxlength="150"></div><div class="field"><label for="tamu-asal">Tamu dari mana</label><input id="tamu-asal" name="asal" maxlength="200"></div><div class="field"><label for="tamu-tanggal">Tanggal kedatangan <span class="required">*</span></label><input id="tamu-tanggal" name="tanggal_kedatangan" type="date" required></div><div class="field"><label for="tamu-status">Status <span class="required">*</span></label><select id="tamu-status" name="status" required><option>Akan Datang</option><option>Sudah Datang</option><option>Keluar Site</option><option>Batal</option></select></div><div class="field full-width" id="tamu-keluar-field" hidden><label for="tamu-keluar">Tanggal keluar site <span class="required">*</span></label><input id="tamu-keluar" name="tanggal_keluar" type="date"></div><div class="field full-width"><label for="tamu-keperluan">Keperluan</label><input id="tamu-keperluan" name="keperluan" maxlength="500"></div><div class="field full-width"><label for="tamu-note">Note</label><textarea id="tamu-note" name="catatan" rows="4" maxlength="3000"></textarea></div>`);
const noteDialog=makeDialog('catatan-dialog','Tambah catatan',`<div class="field full-width"><label for="catatan-jenis">Jenis catatan <span class="required">*</span></label><select id="catatan-jenis" name="jenis" required><option>Administrasi Karyawan</option><option>Pengingat</option></select></div><div class="field full-width" id="catatan-employee-picker"></div><div class="field full-width" id="catatan-tanggal-field" hidden><label for="catatan-tanggal">Tanggal pengingat <span class="required">*</span></label><input id="catatan-tanggal" name="tanggal_pengingat" type="date"></div><div class="field full-width"><label for="catatan-note">Note <span class="required">*</span></label><textarea id="catatan-note" name="catatan" rows="5" required maxlength="3000"></textarea></div>`);
const picker=g.EmployeeUI.createPicker('catatan-employee','Karyawan',{allowAdmin:false,allowExistingInactive:true});
let guests=[],notes=[],employees=[],tab='tamu',editingGuest=null,editingNote=null,request=0;
const stamp=v=>v?new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jayapura',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))+' WIT':'—';
const guestActive=g=>!['Keluar Site','Batal'].includes(g.status);
function error(id,msg){$(id).textContent=msg;$(id).hidden=!msg;}
function render(){
 $('agenda-add').hidden=!A.canWrite();
 if(!A.canWrite()){$('agenda-results').innerHTML='<p class="agenda-empty">Halaman ini tersedia untuk admin dengan akses Portal.</p>';$('agenda-count').textContent='';return;}
 const active=$('agenda-view').value==='aktif';let rows;
 if(tab==='tamu'){
  rows=guests.filter(g=>guestActive(g)===active).sort((a,b)=>active?a.tanggal_kedatangan.localeCompare(b.tanggal_kedatangan)||a.nama.localeCompare(b.nama,'id-ID'):(b.tanggal_keluar||b.tanggal_kedatangan).localeCompare(a.tanggal_keluar||a.tanggal_kedatangan));
  $('agenda-results').innerHTML=rows.length?`<div class="table-scroll"><table class="agenda-table"><thead><tr><th>Tamu / asal</th><th>Kedatangan</th><th>Status / keluar</th><th>Keperluan &amp; note</th><th>Tindakan</th></tr></thead><tbody>${rows.map(g=>`<tr><td data-label="Tamu / asal"><strong>${e(g.nama)}</strong><span class="secondary-value">${e(g.asal||'—')}</span></td><td data-label="Kedatangan">${e(U.dateText(g.tanggal_kedatangan))}</td><td data-label="Status / keluar"><span class="status-badge">${e(g.status)}</span>${g.tanggal_keluar?`<span class="secondary-value">${e(U.dateText(g.tanggal_keluar))}</span>`:''}</td><td data-label="Keperluan & note"><div class="agenda-note">${e(g.keperluan||'—')}</div>${g.catatan?`<p class="agenda-note">${e(g.catatan)}</p>`:''}<small>Dibuat: ${e(g.nama_pembuat)} · ${e(stamp(g.dibuat_pada))}</small><small>Diubah: ${e(g.nama_pengubah)} · ${e(stamp(g.diubah_pada))}</small></td><td data-label="Tindakan"><div class="agenda-actions"><button type="button" class="button button-secondary" data-tamu-edit="${e(g.id)}">Edit${guestActive(g)?' / Keluar site':''}</button>${window.DataAdmin.buttons('tamu',g.id,g.versi,g.nama)}</div></td></tr>`).join('')}</tbody></table></div>`:'<p class="agenda-empty">Belum ada tamu pada daftar ini.</p>';
 }else{
  rows=notes.filter(n=>(n.status==='Aktif')===active&&(!$('agenda-category').value||n.jenis===$('agenda-category').value)).sort((a,b)=>(a.tanggal_pengingat||'9999').localeCompare(b.tanggal_pengingat||'9999')||b.dibuat_pada.localeCompare(a.dibuat_pada));
  $('agenda-results').innerHTML=rows.length?`<ul class="agenda-notes">${rows.map(n=>{const w=warning(n),person=employees.find(p=>p.id===n.karyawan_id);return `<li class="agenda-card ${w.kind}"><div class="agenda-card-top"><span class="agenda-kind">${e(n.jenis)}</span>${w.label?`<span class="agenda-warning ${w.kind}">${e(w.label)}</span>`:''}</div>${n.jenis==='Administrasi Karyawan'?`<h2>${e(person?.nama||'Karyawan')} <small>${e(person?.nik||'')}</small></h2>`:`<h2>${e(U.dateText(n.tanggal_pengingat))}</h2>`}<p class="agenda-note">${e(n.catatan)}</p><div class="agenda-meta"><span>Dibuat oleh <strong>${e(n.nama_pembuat)}</strong> · ${e(stamp(n.dibuat_pada))}</span>${n.status==='Selesai'?`<span>Diselesaikan oleh <strong>${e(n.nama_penyelesai)}</strong> · ${e(stamp(n.diselesaikan_pada))}</span>`:''}<span>Terakhir diubah: ${e(n.nama_pengubah)} · ${e(stamp(n.diubah_pada))}</span></div><div class="agenda-actions">${n.status==='Aktif'?`<button type="button" class="button button-primary" data-note-status="Selesai" data-note-id="${e(n.id)}">Tandai Selesai</button><button type="button" class="button button-secondary" data-note-edit="${e(n.id)}">Edit</button>`:A.administrator()?`<button type="button" class="button button-secondary" data-note-status="Aktif" data-note-id="${e(n.id)}">Buka kembali</button>`:''}${g.DataAdmin.buttons('catatan',n.id,n.versi,n.catatan.slice(0,100))}</div></li>`;}).join('')}</ul>`:'<p class="agenda-empty">Belum ada catatan pada daftar ini.</p>';
 }
 $('agenda-count').textContent=rows.length+' '+(tab==='tamu'?'tamu':'catatan');
}
async function refresh(){const n=++request;await A.ready;if(!A.canWrite()){guests=[];notes=[];employees=[];render();return;}try{const data=await Promise.all([A.all('tamu'),A.all('catatan_admin'),g.EmployeeStore.list()]);if(n!==request)return;[guests,notes,employees]=data;error('agenda-error','');render();}catch(err){if(n===request)error('agenda-error',err.message);}}
function selectTab(next){tab=next;$('agenda-view').value='aktif';$('agenda-view').options[1].textContent=tab==='tamu'?'Riwayat':'Selesai';$('agenda-add').textContent=tab==='tamu'?'Tambah tamu':'Tambah catatan';$('agenda-category-field').hidden=tab==='tamu';document.querySelectorAll('[data-agenda-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.agendaTab===tab));b.tabIndex=b.dataset.agendaTab===tab?0:-1;});$('agenda-results').setAttribute('aria-labelledby','agenda-tab-'+tab);render();}
function guestStatus(){const out=$('tamu-status').value==='Keluar Site';$('tamu-keluar-field').hidden=!out;$('tamu-keluar').required=out;$('tamu-keluar').disabled=!out;$('tamu-keluar').min=$('tamu-tanggal').value;$('tamu-keluar').max=D.today();if(!out)$('tamu-keluar').value='';}
function noteType(){const employee=$('catatan-jenis').value==='Administrasi Karyawan';$('catatan-employee-picker').hidden=!employee;picker.setDisabled(!employee);$('catatan-tanggal-field').hidden=employee;$('catatan-tanggal').required=!employee;$('catatan-tanggal').disabled=employee;}
async function guestForm(id){if(!A.canWrite())return;editingGuest=id?await A.one('tamu',id):null;const f=$('tamu-dialog-form');f.reset();for(const el of f.elements)if(el.name)el.value=editingGuest?.[el.name]??({tanggal_kedatangan:D.today(),status:'Akan Datang'}[el.name]||'');guestStatus();$('tamu-dialog-title').textContent=id?'Edit tamu':'Tambah tamu';error('tamu-dialog-error','');guestDialog.querySelector('[data-current-user]').textContent=A.profile?.nama||'';guestDialog.showModal();$('tamu-nama').focus();}
async function noteForm(id){if(!A.canWrite())return;editingNote=id?await A.one('catatan_admin',id):null;const f=$('catatan-dialog-form');f.reset();$('catatan-jenis').value=editingNote?.jenis||'Administrasi Karyawan';$('catatan-tanggal').value=editingNote?.tanggal_pengingat||'';$('catatan-note').value=editingNote?.catatan||'';await picker.load(editingNote?.karyawan_id||'');noteType();$('catatan-dialog-title').textContent=id?'Edit catatan':'Tambah catatan';error('catatan-dialog-error','');noteDialog.querySelector('[data-current-user]').textContent=A.profile?.nama||'';noteDialog.showModal();$('catatan-jenis').focus();}
$('agenda-add').onclick=()=>{(tab==='tamu'?guestForm():noteForm()).catch(err=>error('agenda-error',err.message));};
$('agenda-refresh').onclick=refresh;$('agenda-view').onchange=$('agenda-category').onchange=render;
$('tamu-status').onchange=$('tamu-tanggal').onchange=guestStatus;$('catatan-jenis').onchange=noteType;
document.querySelectorAll('[data-agenda-close]').forEach(b=>b.onclick=()=>$(b.dataset.agendaClose).close());
document.querySelectorAll('[data-agenda-tab]').forEach(b=>{b.onclick=()=>selectTab(b.dataset.agendaTab);b.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();selectTab(event.key==='Home'?'tamu':event.key==='End'?'catatan':tab==='tamu'?'catatan':'tamu');$('agenda-tab-'+tab).focus();}};});
host.addEventListener('click',async event=>{const editGuest=event.target.closest('[data-tamu-edit]'),editNote=event.target.closest('[data-note-edit]'),done=event.target.closest('[data-note-status]');try{if(editGuest)await guestForm(editGuest.dataset.tamuEdit);if(editNote)await noteForm(editNote.dataset.noteEdit);if(done&&!done.disabled){done.disabled=true;const n=notes.find(n=>n.id===done.dataset.noteId);await A.rpc('ubah_status_catatan',{p_id:n.id,p_versi:n.versi,p_status:done.dataset.noteStatus},true);await refresh();U.showToast(done.dataset.noteStatus==='Selesai'?'Catatan selesai.':'Catatan dibuka kembali.');}}catch(err){error('agenda-error',err.message);}finally{if(done)done.disabled=false;}});
for(const kind of ['tamu','catatan']){$(kind+'-dialog-form').onsubmit=async event=>{event.preventDefault();const f=event.currentTarget,b=f.querySelector('[type=submit]');if(b.disabled||!f.reportValidity())return;b.disabled=true;try{const data=Object.fromEntries(new FormData(f)),old=kind==='tamu'?editingGuest:editingNote;if(kind==='catatan')data.karyawan_id=data.jenis==='Administrasi Karyawan'?picker.read().employeeId:null;await A.rpc(kind==='tamu'?'simpan_tamu':'simpan_catatan_admin',{p_data:data,...(old?{p_id:old.id,p_versi:old.versi}:{})},true);g.FormGuard?.clean(f);$(kind+'-dialog').close();await refresh();U.showToast(kind==='tamu'?'Data tamu tersimpan.':'Catatan tersimpan.');}catch(err){error(kind+'-dialog-error',err.message);}finally{b.disabled=false;}};}
for(const name of ['akses:berubah','data:muat-ulang','employees:changed'])document.addEventListener(name,refresh);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});setInterval(()=>{if(!document.hidden&&location.hash==='#agenda')refresh();},60000);refresh();
})(window);
